import 'dart:convert';
import 'package:ai_chan/services/ai_service.dart';
import 'package:ai_chan/core/models.dart';

class FakeAIServiceImpl extends AIService {
  @override
  Future<AIResponse> sendMessageImpl(
    List<Map<String, String>> history,
    SystemPrompt systemPrompt, {
    String? model,
    String? imageBase64,
    String? imageMimeType,
    bool enableImageGeneration = false,
  }) async {
    // Return a minimal valid JSON block as if it were generated by AI.
    final json = {
      'datos_personales': {'nombre_completo': 'Ai Test'},
      'personalidad': {
        'valores': {'Sociabilidad': '5'},
      },
      'resumen_breve': 'Resumen de prueba',
    };
    final text = jsonEncode(json);
    return AIResponse(text: text, base64: '', seed: '', prompt: '');
  }

  @override
  Future<List<String>> getAvailableModels() async {
    return ['fake-model'];
  }
}
