class CountryItem {
  final String nameEs;
  final String iso2;
  const CountryItem(this.nameEs, this.iso2);
}

/// Lista ordenada de países (nombre en español → código ISO2) según la selección del usuario.
class CountriesEs {
  static const List<CountryItem> items = [
    CountryItem('España', 'ES'),
    CountryItem('Francia', 'FR'),
    CountryItem('Italia', 'IT'),
    CountryItem('Portugal', 'PT'),
    CountryItem('Alemania', 'DE'),
    CountryItem('Reino Unido', 'GB'),
    CountryItem('Irlanda', 'IE'),
    CountryItem('Bélgica', 'BE'),
    CountryItem('Países Bajos (Holanda)', 'NL'),
    CountryItem('Suiza', 'CH'),
    CountryItem('Austria', 'AT'),
    CountryItem('Grecia', 'GR'),
    CountryItem('Polonia', 'PL'),
    CountryItem('Hungría', 'HU'),
    CountryItem('República Checa', 'CZ'),
    CountryItem('Noruega', 'NO'),
    CountryItem('Suecia', 'SE'),
    CountryItem('Finlandia', 'FI'),
    CountryItem('Dinamarca', 'DK'),
    CountryItem('Islandia', 'IS'),
    CountryItem('Rusia', 'RU'),
    CountryItem('Ucrania', 'UA'),
    CountryItem('Rumanía', 'RO'),
    CountryItem('Bulgaria', 'BG'),
    CountryItem('Croacia', 'HR'),
    CountryItem('Serbia', 'RS'),
    CountryItem('Turquía', 'TR'),
    CountryItem('Malta', 'MT'),
    CountryItem('Andorra', 'AD'),
    CountryItem('Eslovenia', 'SI'),
    CountryItem('Eslovaquia', 'SK'),
    CountryItem('Montenegro', 'ME'),
    CountryItem('Bosnia y Herzegovina', 'BA'),
    CountryItem('Estonia', 'EE'),
    CountryItem('Letonia', 'LV'),
    CountryItem('Estados Unidos', 'US'),
    CountryItem('Canadá', 'CA'),
    CountryItem('México', 'MX'),
    CountryItem('Cuba', 'CU'),
    CountryItem('República Dominicana', 'DO'),
    CountryItem('Puerto Rico', 'PR'),
    CountryItem('Costa Rica', 'CR'),
    CountryItem('Panamá', 'PA'),
    CountryItem('Guatemala', 'GT'),
    CountryItem('Honduras', 'HN'),
    CountryItem('El Salvador', 'SV'),
    CountryItem('Nicaragua', 'NI'),
    CountryItem('Colombia', 'CO'),
    CountryItem('Venezuela', 'VE'),
    CountryItem('Ecuador', 'EC'),
    CountryItem('Perú', 'PE'),
    CountryItem('Bolivia', 'BO'),
    CountryItem('Chile', 'CL'),
    CountryItem('Argentina', 'AR'),
    CountryItem('Brasil', 'BR'),
    CountryItem('Paraguay', 'PY'),
    CountryItem('Uruguay', 'UY'),
    CountryItem('Haití', 'HT'),
    CountryItem('Jamaica', 'JM'),
    CountryItem('Marruecos', 'MA'),
    CountryItem('Argelia', 'DZ'),
    CountryItem('Túnez', 'TN'),
    CountryItem('Egipto', 'EG'),
    CountryItem('Sudán', 'SD'),
    CountryItem('Libia', 'LY'),
    CountryItem('Senegal', 'SN'),
    CountryItem('Gambia', 'GM'),
    CountryItem('Ghana', 'GH'),
    CountryItem('Nigeria', 'NG'),
    CountryItem('Etiopía', 'ET'),
    CountryItem('Kenia', 'KE'),
    CountryItem('Tanzania', 'TZ'),
    CountryItem('Uganda', 'UG'),
    CountryItem('República Democrática del Congo', 'CD'),
    CountryItem('Angola', 'AO'),
    CountryItem('Mozambique', 'MZ'),
    CountryItem('Madagascar', 'MG'),
    CountryItem('Sudáfrica', 'ZA'),
    CountryItem('Guinea Ecuatorial', 'GQ'),
    CountryItem('China', 'CN'),
    CountryItem('Japón', 'JP'),
    CountryItem('Corea del Sur', 'KR'),
    CountryItem('Corea del Norte', 'KP'),
    CountryItem('India', 'IN'),
    CountryItem('Pakistán', 'PK'),
    CountryItem('Nepal', 'NP'),
    CountryItem('Sri Lanka', 'LK'),
    CountryItem('Tailandia', 'TH'),
    CountryItem('Vietnam', 'VN'),
    CountryItem('Camboya', 'KH'),
    CountryItem('Laos', 'LA'),
    CountryItem('Birmania (Myanmar)', 'MM'),
    CountryItem('Malasia', 'MY'),
    CountryItem('Singapur', 'SG'),
    CountryItem('Indonesia', 'ID'),
    CountryItem('Filipinas', 'PH'),
    CountryItem('Israel', 'IL'),
    CountryItem('Australia', 'AU'),
    CountryItem('Nueva Zelanda', 'NZ'),
    CountryItem('Fiyi', 'FJ'),
  ];

  static const Map<String, String> nameToIso = {
    'España': 'ES',
    'Francia': 'FR',
    'Italia': 'IT',
    'Portugal': 'PT',
    'Alemania': 'DE',
    'Reino Unido': 'GB',
    'Irlanda': 'IE',
    'Bélgica': 'BE',
    'Países Bajos (Holanda)': 'NL',
    'Suiza': 'CH',
    'Austria': 'AT',
    'Grecia': 'GR',
    'Polonia': 'PL',
    'Hungría': 'HU',
    'República Checa': 'CZ',
    'Noruega': 'NO',
    'Suecia': 'SE',
    'Finlandia': 'FI',
    'Dinamarca': 'DK',
    'Islandia': 'IS',
    'Rusia': 'RU',
    'Ucrania': 'UA',
    'Rumanía': 'RO',
    'Bulgaria': 'BG',
    'Croacia': 'HR',
    'Serbia': 'RS',
    'Turquía': 'TR',
    'Malta': 'MT',
    'Andorra': 'AD',
    'Eslovenia': 'SI',
    'Eslovaquia': 'SK',
    'Montenegro': 'ME',
    'Bosnia y Herzegovina': 'BA',
    'Estonia': 'EE',
    'Letonia': 'LV',
    'Estados Unidos': 'US',
    'Canadá': 'CA',
    'México': 'MX',
    'Cuba': 'CU',
    'República Dominicana': 'DO',
    'Puerto Rico': 'PR',
    'Costa Rica': 'CR',
    'Panamá': 'PA',
    'Guatemala': 'GT',
    'Honduras': 'HN',
    'El Salvador': 'SV',
    'Nicaragua': 'NI',
    'Colombia': 'CO',
    'Venezuela': 'VE',
    'Ecuador': 'EC',
    'Perú': 'PE',
    'Bolivia': 'BO',
    'Chile': 'CL',
    'Argentina': 'AR',
    'Brasil': 'BR',
    'Paraguay': 'PY',
    'Uruguay': 'UY',
    'Haití': 'HT',
    'Jamaica': 'JM',
    'Marruecos': 'MA',
    'Argelia': 'DZ',
    'Túnez': 'TN',
    'Egipto': 'EG',
    'Sudán': 'SD',
    'Libia': 'LY',
    'Senegal': 'SN',
    'Gambia': 'GM',
    'Ghana': 'GH',
    'Nigeria': 'NG',
    'Etiopía': 'ET',
    'Kenia': 'KE',
    'Tanzania': 'TZ',
    'Uganda': 'UG',
    'República Democrática del Congo': 'CD',
    'Angola': 'AO',
    'Mozambique': 'MZ',
    'Madagascar': 'MG',
    'Sudáfrica': 'ZA',
    'Guinea Ecuatorial': 'GQ',
    'China': 'CN',
    'Japón': 'JP',
    'Corea del Sur': 'KR',
    'Corea del Norte': 'KP',
    'India': 'IN',
    'Pakistán': 'PK',
    'Nepal': 'NP',
    'Sri Lanka': 'LK',
    'Tailandia': 'TH',
    'Vietnam': 'VN',
    'Camboya': 'KH',
    'Laos': 'LA',
    'Birmania (Myanmar)': 'MM',
    'Malasia': 'MY',
    'Singapur': 'SG',
    'Indonesia': 'ID',
    'Filipinas': 'PH',
    'Israel': 'IL',
    'Australia': 'AU',
    'Nueva Zelanda': 'NZ',
    'Fiyi': 'FJ',
  };

  static const Map<String, String> codeToName = {
    'ES': 'España',
    'FR': 'Francia',
    'IT': 'Italia',
    'PT': 'Portugal',
    'DE': 'Alemania',
    'GB': 'Reino Unido',
    'IE': 'Irlanda',
    'BE': 'Bélgica',
    'NL': 'Países Bajos (Holanda)',
    'CH': 'Suiza',
    'AT': 'Austria',
    'GR': 'Grecia',
    'PL': 'Polonia',
    'HU': 'Hungría',
    'CZ': 'República Checa',
    'NO': 'Noruega',
    'SE': 'Suecia',
    'FI': 'Finlandia',
    'DK': 'Dinamarca',
    'IS': 'Islandia',
    'RU': 'Rusia',
    'UA': 'Ucrania',
    'RO': 'Rumanía',
    'BG': 'Bulgaria',
    'HR': 'Croacia',
    'RS': 'Serbia',
    'TR': 'Turquía',
    'MT': 'Malta',
    'AD': 'Andorra',
    'SI': 'Eslovenia',
    'SK': 'Eslovaquia',
    'ME': 'Montenegro',
    'BA': 'Bosnia y Herzegovina',
    'EE': 'Estonia',
    'LV': 'Letonia',
    'US': 'Estados Unidos',
    'CA': 'Canadá',
    'MX': 'México',
    'CU': 'Cuba',
    'DO': 'República Dominicana',
    'PR': 'Puerto Rico',
    'CR': 'Costa Rica',
    'PA': 'Panamá',
    'GT': 'Guatemala',
    'HN': 'Honduras',
    'SV': 'El Salvador',
    'NI': 'Nicaragua',
    'CO': 'Colombia',
    'VE': 'Venezuela',
    'EC': 'Ecuador',
    'PE': 'Perú',
    'BO': 'Bolivia',
    'CL': 'Chile',
    'AR': 'Argentina',
    'BR': 'Brasil',
    'PY': 'Paraguay',
    'UY': 'Uruguay',
    'HT': 'Haití',
    'JM': 'Jamaica',
    'MA': 'Marruecos',
    'DZ': 'Argelia',
    'TN': 'Túnez',
    'EG': 'Egipto',
    'SD': 'Sudán',
    'LY': 'Libia',
    'SN': 'Senegal',
    'GM': 'Gambia',
    'GH': 'Ghana',
    'NG': 'Nigeria',
    'ET': 'Etiopía',
    'KE': 'Kenia',
    'TZ': 'Tanzania',
    'UG': 'Uganda',
    'CD': 'República Democrática del Congo',
    'AO': 'Angola',
    'MZ': 'Mozambique',
    'MG': 'Madagascar',
    'ZA': 'Sudáfrica',
    'GQ': 'Guinea Ecuatorial',
    'CN': 'China',
    'JP': 'Japón',
    'KR': 'Corea del Sur',
    'KP': 'Corea del Norte',
    'IN': 'India',
    'PK': 'Pakistán',
    'NP': 'Nepal',
    'LK': 'Sri Lanka',
    'TH': 'Tailandia',
    'VN': 'Vietnam',
    'KH': 'Camboya',
    'LA': 'Laos',
    'MM': 'Birmania (Myanmar)',
    'MY': 'Malasia',
    'SG': 'Singapur',
    'ID': 'Indonesia',
    'PH': 'Filipinas',
    'IL': 'Israel',
    'AU': 'Australia',
    'NZ': 'Nueva Zelanda',
    'FJ': 'Fiyi',
  };
}
