import 'package:flutter_test/flutter_test.dart';
import 'package:ai_chan/core/services/ia_bio_generator.dart';
import 'package:ai_chan/core/models.dart';
import 'dart:convert';
import 'package:ai_chan/services/ai_service.dart';

class FakeAIServiceImpl extends AIService {
  @override
  Future<AIResponse> sendMessageImpl(
    List<Map<String, String>> history,
    SystemPrompt systemPrompt, {
    String? model,
    String? imageBase64,
    String? imageMimeType,
    bool enableImageGeneration = false,
  }) async {
    // Return a minimal valid JSON block as if it were generated by AI.
    final json = {
      'datos_personales': {'nombre_completo': 'Ai Test'},
      'personalidad': {
        'valores': {'Sociabilidad': '5'},
      },
      'resumen_breve': 'Resumen de prueba',
    };
    final text = jsonEncode(json);
    return AIResponse(text: text, base64: '', seed: '', prompt: '');
  }

  @override
  Future<List<String>> getAvailableModels() async {
    return ['fake-model'];
  }
}

void main() {
  test('generateAIBiographyWithAI returns AiChanProfile given fake AIService', () async {
    // Inject the fake
    AIService.testOverride = FakeAIServiceImpl();

    final profile = await generateAIBiographyWithAI(
      userName: 'UserTest',
      aiName: 'AiTest',
      userBirthday: DateTime(1995, 6, 15),
      meetStory: 'Una historia de prueba',
      userCountryCode: 'ES',
      aiCountryCode: 'JP',
      seed: 42,
    );

    expect(profile, isA<AiChanProfile>());
    expect(profile.biography, contains('resumen_breve'));

    // Clear override
    AIService.testOverride = null;
  });
}
