name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Run analyzer
        run: flutter analyze
      - name: Run tests (fast)
        run: flutter test test/migration/import_sanity_test.dart test/chat/chat_provider_test.dart test/calls/gemini_orchestrator_test.dart -r expanded
