name: CI

on:
  push:
    branches: ["main", "migration"]
  pull_request:
    branches: ["main", "migration"]

jobs:
  analyze-and-test:
    name: Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage
