name: Flutter CI

on:
  pull_request:
    branches: [ "migration", "main" ]
  push:
    branches: [ "migration" ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Run unit tests
        run: flutter test --coverage

      - name: Upload test results (optional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: coverage
